#spring:
#  datasource:
#    url: jdbc:h2:tcp://localhost/~/test
#    username: sa
#    password: 1
#    driver-class-name: org.h2.Driver
#
#  jpa:
#    database: H2
#    show-sql: true
#    hibernate:
#      ddl-auto: none