# 예제에서는 persistence.xml로 Configuration을 하고 있기 때문에 사용하지 않는다.
#spring:
#  datasource:
#    url: jdbc:h2:tcp://localhost/~/test
#    username: sa
#    password:
#    driver-class-name: org.h2.Driver
#
#  jpa:
#    database: H2
##    show-sql: true
#    hibernate:
#      ddl-auto: none
#
#
#logging:
#  level:
#    org.hibernate.sql: debug